export declare function useAgendamentos(): {
    todosAgendamentos: {
        clienteNome: string;
        servicoNome: string;
        servicoValor: number;
        servicoDuracao: number;
        clienteEmail: string;
        clienteTelefone: string;
        servicoDescricao: string;
        id: string;
        clienteId: string;
        servicoId: string;
        data: string;
        hora: string;
        duracao: number;
        valor: number;
        valorPago: number;
        valorDevido: number;
        formaPagamento: "dinheiro" | "cartao" | "pix" | "fiado";
        statusPagamento: "pago" | "parcial" | "em_aberto";
        status: "agendado" | "concluido" | "cancelado" | "excluido";
        observacoes?: string;
        origem?: "manual" | "cronograma" | "online";
        origem_cronograma: boolean;
        cronogramaId?: string;
        confirmado?: boolean;
        dataPrevistaPagamento?: string;
        createdAt: string;
        updatedAt: string;
    }[];
    agendamentosFiltrados: {
        clienteNome: string;
        servicoNome: string;
        servicoValor: number;
        servicoDuracao: number;
        clienteEmail: string;
        clienteTelefone: string;
        servicoDescricao: string;
        id: string;
        clienteId: string;
        servicoId: string;
        data: string;
        hora: string;
        duracao: number;
        valor: number;
        valorPago: number;
        valorDevido: number;
        formaPagamento: "dinheiro" | "cartao" | "pix" | "fiado";
        statusPagamento: "pago" | "parcial" | "em_aberto";
        status: "agendado" | "concluido" | "cancelado" | "excluido";
        observacoes?: string;
        origem?: "manual" | "cronograma" | "online";
        origem_cronograma: boolean;
        cronogramaId?: string;
        confirmado?: boolean;
        dataPrevistaPagamento?: string;
        createdAt: string;
        updatedAt: string;
    }[];
    clientes: import("../types/cliente").Cliente[];
    servicos: import("../types/servico").Servico[];
    verificarConflito: (agendamento: any, excluirId?: string) => boolean;
    criarAgendamento: (novoAgendamento: any) => Promise<boolean>;
    adicionarAgendamentosCronograma: () => void;
    verificarHorarioDisponivel: (data: string, hora: string) => Promise<boolean>;
    loading: boolean;
    agendamentos: import("../types/agendamento").Agendamento[];
    filtros: import("../types/agendamento").AgendamentoFiltros;
    setFiltros: import("react").Dispatch<import("react").SetStateAction<import("../types/agendamento").AgendamentoFiltros>>;
    paginaAtual: number;
    setPaginaAtual: import("react").Dispatch<import("react").SetStateAction<number>>;
    totalPaginas: number;
    atualizarAgendamento: (id: string, dadosAtualizados: any) => Promise<boolean>;
    excluirAgendamento: (id: string) => Promise<boolean>;
    cancelarAgendamento: (id: string) => Promise<boolean>;
    recarregar: (mesFiltroArg?: string) => Promise<void>;
    converterAgendamentoOnlineParaRegular: (agendamentoOnlineId: string) => Promise<boolean>;
    confirmarAgendamentoOnline: (agendamentoOnlineId: string) => Promise<boolean>;
};
//# sourceMappingURL=useAgendamentos.d.ts.map