// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createLoggedFetch } from './loggedFetch';

const VITE_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const VITE_SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? '';

if (!VITE_SUPABASE_URL || !VITE_SUPABASE_ANON_KEY) {
  throw new Error('[Supabase] VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY devem estar definidas. Veja .env.example.');
}

export const SUPABASE_URL = VITE_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = VITE_SUPABASE_ANON_KEY;

const secureFetch = createLoggedFetch({ label: 'supabaseClient', timeoutMs: 45000 });

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: (() => {
      try {
        const hasSessionStorage = typeof window !== 'undefined' && !!window.sessionStorage;
        const hasLocalStorage = typeof window !== 'undefined' && !!window.localStorage;
        return hasLocalStorage && false ? (window.localStorage as any) : hasLocalStorage ? (window.localStorage as any) : undefined;
      } catch {
        return undefined;
      }
    })(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    fetch: secureFetch as any,
    headers: {
      'X-Requested-With': 'XMLHttpRequest',
      'X-Zalu-Client': 'web',
      'Cache-Control': 'no-store',
    },
  },
});

