name: Secret Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
